import React from "react";
import ReactDOM from "react-dom";
// import AdminMembers from "./AdminMembers";
// import AdminRegistration from "./AdminRegistration";
// import App from "./App";
import WebShare from "./components/WebShare";
// import Message from "./components/Message";
// import LoadingPage from "./components/LoadingPage";
// import SuccessAnimation from "./components/SuccessAnimation";
// import PaymentPage from "./user/PaymentPage";
// import ProfilePage from "./user/ProfilePage";
// import UserLogin from "./UserLogin";
// import GameIntro from "./user/GameIntro";
// import Notifications from "./user/Notifications";
// import Home from "./admin/Home";
// import UserRegistration from "./UserRegistration";
// import CreateTeam from "./CreateTeam.jsx";
// import AdminRegistration from "./AdminRegistration";
// import Template from "./user/Template";

ReactDOM.render(<WebShare />, document.getElementById("root"));
