import React from "react";
import ReactDOM from "react-dom";
// import Footer from "./Footer";
// import AdminMembers from "./AdminMembers";
// import AdminRegistration from "./AdminRegistration";
import App from "./App";
// import ScoreNav from "../src/user/ScoreNav";
import Pricing from "./components/Pricing";
// import SampleHomePage from "./SampleHomePage";
// import StickyFooter from "./StickyFooter";
// import Camera from "./components/Camera";
// import Verify from "./components/Verify";
// import WebShare from "./components/WebShare";
// import Message from "./components/Message";
// import LoadingPage from "./components/LoadingPage";
// import SuccessAnimation from "./components/SuccessAnimation";
// import PaymentPage from "./user/PaymentPage";
// import ProfilePage from "./user/ProfilePage";
// import UserLogin from "./UserLogin";
// import GameIntro from "./user/GameIntro";
// import Notifications from "./user/Notifications";
// import Home from "./admin/Home";
// import UserRegistration from "./UserRegistration";
// import CreateTeam from "./CreateTeam.jsx";
// import AdminRegistration from "./AdminRegistration";
// import Template from "./user/Template";
// import * as serviceWorker from "./serviceWorker";
// import PaymentPage from "./user/PaymentPage";
// import Pricing from "./components/Pricing";
// import ForgotPassword from "./user/ForgotPassword";

ReactDOM.render(<App />, document.getElementById("root"));
